version: "3.8"

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpass
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - mariadb_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_mariadb
    restart: unless-stopped
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpass
    ports:
      - "8081:80"
    volumes:
      - phpmyadmin_mariadb_data:/var/www/html
    networks:
      - mariadb_network

volumes:
  mariadb_data:
  phpmyadmin_mariadb_data:

networks:
  mariadb_network:
    driver: bridge
